language: node_js
node_js:
  - '8'
  - '6'
  - '5'
  - '4'
before_script:
  - git config --global user.name "Daniel Perez"
  - git config --global user.email "tuvistavie@gmail.com"
before_install: npm install -g grunt-cli
script: grunt coverage
notifications:
  email: false
